---
apiVersion: v1
kind: Namespace
metadata:
  name: kitops
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kitops
  namespace: kitops
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kitops
    namespace: kitops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: kitops
  name: kitops
  namespace: kitops
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: kitops
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: kitops
    spec:
      containers:
      - image: 300481/kitops:latest
        imagePullPolicy: Always
        name: kitops
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      restartPolicy: Always
      serviceAccountName: kitops
